## This file is a general .xdc for the Basys3 rev B board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used ports (in each line, after get_ports) according to the top level signal names in the project

## Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
## Switches
set_property PACKAGE_PIN V17 [get_ports {leftIn[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[0]}]
set_property PACKAGE_PIN V16 [get_ports {leftIn[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[1]}]
set_property PACKAGE_PIN W16 [get_ports {leftIn[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[2]}]
set_property PACKAGE_PIN W17 [get_ports {leftIn[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[3]}]
set_property PACKAGE_PIN W15 [get_ports {leftIn[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[4]}]
set_property PACKAGE_PIN V15 [get_ports {leftIn[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[5]}]
set_property PACKAGE_PIN W14 [get_ports {leftIn[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[6]}]
set_property PACKAGE_PIN W13 [get_ports {leftIn[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftIn[7]}]
set_property PACKAGE_PIN V2 [get_ports {rightIn[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[0]}]
set_property PACKAGE_PIN T3 [get_ports {rightIn[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[1]}]
set_property PACKAGE_PIN T2 [get_ports {rightIn[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[2]}]
set_property PACKAGE_PIN R3 [get_ports {rightIn[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[3]}]
set_property PACKAGE_PIN W2 [get_ports {rightIn[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[4]}]
set_property PACKAGE_PIN U1 [get_ports {rightIn[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[5]}]
set_property PACKAGE_PIN T1 [get_ports {rightIn[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[6]}]
set_property PACKAGE_PIN R2 [get_ports {rightIn[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightIn[7]}]
 

## LEDs
set_property PACKAGE_PIN U16 [get_ports {leftOut[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[0]}]
set_property PACKAGE_PIN E19 [get_ports {leftOut[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[1]}]
set_property PACKAGE_PIN U19 [get_ports {leftOut[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[2]}]
set_property PACKAGE_PIN V19 [get_ports {leftOut[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[3]}]
set_property PACKAGE_PIN W18 [get_ports {leftOut[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[4]}]
set_property PACKAGE_PIN U15 [get_ports {leftOut[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[5]}]
set_property PACKAGE_PIN U14 [get_ports {leftOut[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[6]}]
set_property PACKAGE_PIN V14 [get_ports {leftOut[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {leftOut[7]}]
set_property PACKAGE_PIN V13 [get_ports {rightOut[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[0]}]
set_property PACKAGE_PIN V3 [get_ports {rightOut[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[1]}]
set_property PACKAGE_PIN W3 [get_ports {rightOut[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[2]}]
set_property PACKAGE_PIN U3 [get_ports {rightOut[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[3]}]
set_property PACKAGE_PIN P3 [get_ports {rightOut[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[4]}]
set_property PACKAGE_PIN N3 [get_ports {rightOut[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[5]}]
set_property PACKAGE_PIN P1 [get_ports {rightOut[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[6]}]
set_property PACKAGE_PIN L1 [get_ports {rightOut[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rightOut[7]}]
	
	
##7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]
#set_property PACKAGE_PIN V7 [get_ports dp]							
#	set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}]
